import argparse
import json
import os
import queue
import re
import subprocess
import sys
import threading
import time
from pathlib import Path
from tkinter import BOTH, END, LEFT, RIGHT, X, Button, Canvas, Checkbutton, Entry, Frame, Label, Listbox, PhotoImage, StringVar, Text, Tk, filedialog, ttk

import psutil

from game_profiles import PROFILES
from generator_backend import GENERATOR_EXE, best_geometry_jsons, build_generator_command, generated_jsons, generated_preview_files, generator_preview_path, load_settings, write_custom_settings


ROOT = Path(__file__).resolve().parent
PROBE_DIR = ROOT / "webui-data" / "probes"
SESSION_PATH = PROBE_DIR / "current-fh6-session.json"
MEMORY_SNAPSHOT_LIMIT_MB = 2048
PREVIEW_MAX = 520
_CV2_CACHE = None
_CV2_ERROR = None


TEXT = {
    "en": {
        "title": "forza-painter FH6",
        "subtitle": "Generate geometry JSON and import it into Forza Horizon vinyl editor.",
        "language": "Language",
        "process": "Game process",
        "refresh": "Refresh",
        "generate_tab": "Generate JSON",
        "import_tab": "Import",
        "tools_tab": "FH6 Tools",
        "tutorial_tab": "Tutorial",
        "images": "Images",
        "add_images": "Add images",
        "quality": "Quality profile",
        "custom_settings": "Use custom settings",
        "custom_layers": "Output layers",
        "custom_resolution": "Max resolution",
        "custom_random": "Random samples",
        "custom_mutated": "Mutated samples",
        "custom_save_at": "Save checkpoints",
        "generate_step_image": "Step 1 - Choose images",
        "generate_step_image_hint": "Add PNG/JPG/BMP images. Generated JSON is saved beside each source image.",
        "generate_step_quality": "Step 2 - Choose quality",
        "generate_step_quality_hint": "Fast profiles are quicker. Slow profiles use more GPU time and usually look cleaner.",
        "generate_step_run": "Step 3 - Generate",
        "generate_step_run_hint": "Click once and wait. Progress appears in Logs; generated JSON is added to the Import page automatically.",
        "scroll_hint": "Scroll this panel for more settings. Generate button stays below.",
        "start_generate": "Start generating",
        "open_output": "Open output folder",
        "preview": "Preview",
        "preview_hint": "Select an image or JSON to preview it here.",
        "preview_unavailable": "Preview is unavailable. Install optional preview dependencies, or continue without preview.",
        "logs": "Logs",
        "json_files": "Geometry JSON files",
        "add_json": "Add JSON",
        "use_outputs": "Use generated JSON",
        "step_game": "Step 1 - Game",
        "step_game_hint": "Start FH6, open Vinyl Group Editor, load an ungrouped sphere template, then refresh the process list.",
        "step_template": "Step 2 - Template",
        "step_template_hint": "Enter the exact layer count shown by your current in-game template.",
        "step_json": "Step 3 - JSON",
        "step_json_hint": "Use the JSON generated by this app, or add a geometry JSON manually.",
        "step_import": "Step 4 - Import",
        "step_import_hint": "Click import once. The app will find the FH6 layer table safely, then write the design.",
        "advanced_options": "Advanced options",
        "show_advanced": "Show advanced",
        "hide_advanced": "Hide advanced",
        "import_preview": "Selected JSON preview",
        "game_profile": "Game profile",
        "pid": "PID",
        "layer_count": "Template layer count",
        "easy_import": "Easy import",
        "easy_import_hint": "For FH6, leave addresses empty. The app will reuse a live session or auto-locate before import.",
        "manual_count": "Layer count address",
        "manual_table": "Layer table address",
        "auto_locate": "Auto-locate FH6",
        "import_json": "Import JSON",
        "diagnose": "Diagnose",
        "save_snapshot": "Save count snapshot",
        "compare_snapshot": "Compare snapshot",
        "snapshot_count": "Snapshot layer count",
        "current_count": "Current layer count",
        "inspect_table": "Inspect table",
        "table_address": "Candidate table",
        "admin_note": "Import needs administrator permission. Start this app as administrator if OpenProcess fails.",
        "no_game": "No supported game process detected",
        "ready": "Ready",
        "running": "Running",
        "done": "Done",
        "failed": "Failed",
        "locating": "Finding current FH6 template...",
        "located": "FH6 template located and verified.",
        "importing": "Importing JSON into FH6...",
        "json_too_small": "Selected JSON has far fewer drawable layers than the usable template capacity. Import will look blurry; choose a higher-layer JSON.",
        "json_needs_more_template_layers": "FH needs 4 boundary layers for correct cover/apply behavior. Use a template with at least JSON drawable layers + 4.",
        "safe_stop": "Stopped before writing because no safe FH6 template was found.",
        "tutorial": """Beginner workflow

1. Install 64-bit Python 3.12 if possible, then run install_dependencies.bat.
   NumPy/OpenCV preview is optional; generation and import do not require it.
   JSON generation uses the bundled GPU/OpenCL generator, so keep the graphics driver updated.

2. Start Forza Horizon 6 and enter Create Vinyl Group / Vinyl Group Editor.

3. Load or create a template made of many simple sphere layers. 500 or more layers is recommended. Ungroup the template before importing.

4. In this app, open Generate JSON, add a PNG/JPG/BMP image, choose a quality profile, then click Start generating. If preview dependencies are available, the preview area shows the source image first, then the generated geometry preview when JSON appears.

5. Open Import. Add the generated JSON or click Use generated JSON. Keep Game profile as Forza Horizon 6.

6. Enter the real template layer count currently loaded in-game. For FH6 you normally do not need to type memory addresses. Click Import JSON; the app will auto-locate the live FH6 layer table if needed.

7. If import fails with OpenProcess or permission errors, close the app and run it as administrator. If the game was restarted, entered another menu, or reloaded the template, run Auto-locate FH6 again or import again with the correct layer count.

Notes

- The old FH5 signature chain is kept for compatibility, but FH6/Steam builds should use runtime auto-location.
- Current FH6 addresses are valid only for the current game process and editor state.
- If the app cannot find a safe template, confirm the editor is open, the template is ungrouped, and the layer count is exact.
""",
    },
    "zh": {
        "title": "forza-painter FH6",
        "subtitle": "生成 geometry JSON，并导入到 Forza Horizon 的 Vinyl Group 编辑器。",
        "language": "语言",
        "process": "游戏进程",
        "refresh": "刷新",
        "generate_tab": "生成 JSON",
        "import_tab": "导入",
        "tools_tab": "FH6 工具",
        "tutorial_tab": "教程",
        "images": "图片",
        "add_images": "添加图片",
        "quality": "品质配置",
        "custom_settings": "使用自定义参数",
        "custom_layers": "输出层数",
        "custom_resolution": "最大分辨率",
        "custom_random": "随机样本",
        "custom_mutated": "变异样本",
        "custom_save_at": "保存节点",
        "generate_step_image": "第 1 步 - 选择图片",
        "generate_step_image_hint": "添加 PNG/JPG/BMP 图片。生成的 JSON 会保存在原图片旁边。",
        "generate_step_quality": "第 2 步 - 选择品质",
        "generate_step_quality_hint": "快速配置耗时短；慢速配置会占用更多 GPU 时间，通常画面更干净。",
        "generate_step_run": "第 3 步 - 开始生成",
        "generate_step_run_hint": "点击一次后等待。进度会显示在日志里，生成的 JSON 会自动加入导入页面。",
        "scroll_hint": "此面板可滚动查看更多设置。生成按钮固定在下方。",
        "start_generate": "开始生成",
        "open_output": "打开输出目录",
        "preview": "预览",
        "preview_hint": "选择图片或 JSON 后会在这里预览。",
        "preview_unavailable": "当前环境无法显示预览。可安装可选预览依赖，也可以直接继续生成或导入。",
        "logs": "日志",
        "json_files": "Geometry JSON 文件",
        "add_json": "添加 JSON",
        "use_outputs": "使用已生成 JSON",
        "step_game": "第 1 步 - 游戏",
        "step_game_hint": "启动 FH6，进入 Vinyl Group Editor，载入未分组的球形模板，然后刷新进程列表。",
        "step_template": "第 2 步 - 模板",
        "step_template_hint": "填写游戏里当前模板显示的真实层数。",
        "step_json": "第 3 步 - JSON",
        "step_json_hint": "使用本软件生成的 JSON，或手动添加 geometry JSON。",
        "step_import": "第 4 步 - 导入",
        "step_import_hint": "只点一次导入。软件会安全定位 FH6 图层表，然后写入图案。",
        "advanced_options": "高级选项",
        "show_advanced": "显示高级",
        "hide_advanced": "隐藏高级",
        "import_preview": "已选 JSON 预览",
        "game_profile": "游戏 profile",
        "pid": "PID",
        "layer_count": "模板层数",
        "easy_import": "简化导入",
        "easy_import_hint": "FH6 通常不需要手填地址。留空即可复用当前 session，或在导入前自动定位。",
        "manual_count": "层数地址",
        "manual_table": "图层表地址",
        "auto_locate": "自动定位 FH6",
        "import_json": "导入 JSON",
        "diagnose": "诊断",
        "save_snapshot": "保存层数快照",
        "compare_snapshot": "对比快照",
        "snapshot_count": "快照层数",
        "current_count": "当前层数",
        "inspect_table": "精查 table",
        "table_address": "候选 table",
        "admin_note": "导入需要管理员权限。如果日志出现 OpenProcess 失败，请用管理员身份启动本程序。",
        "no_game": "未检测到支持的游戏进程",
        "ready": "就绪",
        "running": "运行中",
        "done": "完成",
        "failed": "失败",
        "locating": "正在查找当前 FH6 模板...",
        "located": "已安全定位并验证 FH6 模板。",
        "importing": "正在导入 JSON 到 FH6...",
        "json_too_small": "当前 JSON 可绘制层数远少于模板可用容量，导入会很糊；请换用更高层数的 JSON。",
        "json_needs_more_template_layers": "FH 需要预留 4 个边界层，才能正常保存封面和贴到车上。模板层数建议至少为 JSON 可绘制层数 + 4。",
        "safe_stop": "未找到安全 FH6 模板，已在写入前停止。",
        "tutorial": """小白流程

1. 尽量安装 64 位 Python 3.12，然后运行 install_dependencies.bat。
   NumPy/OpenCV 预览是可选功能；生成和导入不依赖它。
   JSON 生成使用自带的 GPU/OpenCL 生成器，请保持显卡驱动正常。

2. 启动 Forza Horizon 6，进入 Create Vinyl Group / Vinyl Group Editor。

3. 载入或新建一个由大量 sphere 图层组成的模板。建议 500 层以上。导入前必须先 ungroup。

4. 在本软件的“生成 JSON”页添加 PNG/JPG/BMP 图片，选择品质配置，点击“开始生成”。如果预览依赖可用，预览区会先显示原图，JSON 出现后显示生成后的几何预览。

5. 打开“导入”页，添加生成的 JSON，或点击“使用已生成 JSON”。游戏 profile 保持 Forza Horizon 6。

6. 填写游戏里当前模板的真实层数。FH6 通常不需要手动填写内存地址。点击“导入 JSON”，软件会在需要时自动定位当前 FH6 图层表。

7. 如果日志提示 OpenProcess 或权限失败，请关闭软件，用管理员身份重新运行。如果重启过游戏、切换过菜单或重新加载模板，需要用正确层数重新自动定位或重新导入。

说明

- 旧 FH5 签名链仍保留用于兼容；FH6/Steam 构建优先使用运行时自动定位。
- FH6 地址只对当前游戏进程和当前编辑器状态有效。
- 如果软件找不到安全模板，请确认编辑器仍然打开、模板已经 ungroup、层数填写完全正确。
""",
    },
}


def ensure_dirs():
    PROBE_DIR.mkdir(parents=True, exist_ok=True)


def tr(lang, key):
    return TEXT[lang].get(key, TEXT["en"].get(key, key))


def game_processes():
    names = {name.lower(): key for key, profile in PROFILES.items() for name in profile.process_names}
    found = []
    for proc in psutil.process_iter(["pid", "name", "exe"]):
        try:
            name = proc.info.get("name") or ""
            key = names.get(name.lower())
            if key:
                found.append({
                    "pid": proc.info["pid"],
                    "name": name,
                    "profile": key,
                    "label": f"{name} pid {proc.info['pid']}",
                })
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    return found


def parse_hex_or_empty(value):
    value = str(value or "").strip()
    return value or None


def load_session_location():
    if not SESSION_PATH.exists():
        return None
    try:
        return json.loads(SESSION_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def session_pid_is_live(session, game):
    try:
        pid = int(session.get("pid", -1))
        proc = psutil.Process(pid)
        profile = PROFILES.get(game)
        return bool(profile and proc.name().lower() in [name.lower() for name in profile.process_names])
    except (psutil.Error, TypeError, ValueError):
        return False


def load_cv2():
    global _CV2_CACHE, _CV2_ERROR
    if _CV2_CACHE is not None:
        return _CV2_CACHE
    if _CV2_ERROR is not None:
        return None
    try:
        import cv2
        import numpy as np
        _CV2_CACHE = (cv2, np)
        return _CV2_CACHE
    except BaseException as exc:
        _CV2_ERROR = exc
        return None


def resize_keep_aspect(image, max_size=PREVIEW_MAX):
    loaded = load_cv2()
    if not loaded:
        return image
    cv2, _np = loaded
    height, width = image.shape[:2]
    scale = min(max_size / max(width, height), 1.0)
    if scale < 1.0:
        image = cv2.resize(image, (int(width * scale), int(height * scale)), interpolation=cv2.INTER_AREA)
    return image


def image_to_photo(image):
    loaded = load_cv2()
    if not loaded:
        return None
    cv2, _np = loaded
    image = resize_keep_aspect(image)
    ok, encoded = cv2.imencode(".png", image)
    if not ok:
        return None
    return encoded.tobytes()


def render_source_image(path):
    loaded = load_cv2()
    if not loaded:
        return None
    cv2, _np = loaded
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        return None
    return image_to_photo(image)


def render_geometry_json(path):
    loaded = load_cv2()
    if not loaded:
        return None
    cv2, np = loaded
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        shapes = data["shapes"]
        image_w, image_h = [int(v) for v in shapes[0]["data"][2:]]
        bg_r, bg_g, bg_b, bg_a = [int(v) for v in shapes[0]["color"]]
        preview = np.zeros((image_h, image_w, 3), np.uint8)
        if bg_a > 0:
            preview[:, :] = (bg_b, bg_g, bg_r)
        else:
            preview[:, :] = (38, 38, 38)
            tile = 32
            for y in range(0, image_h, tile):
                for x in range(0, image_w, tile):
                    if ((x // tile) + (y // tile)) % 2 == 0:
                        preview[y:y + tile, x:x + tile] = (58, 58, 58)
        for shape in shapes[1:]:
            color = [int(v) for v in shape.get("color", [])]
            if len(color) == 4 and color[3] <= 0:
                continue
            if int(shape.get("type", 0)) != 16:
                continue
            x, y, w, h, rot_deg = shape["data"]
            r, g, b, _a = color
            center = (int(round(x)), int(round(y)))
            axes = (max(1, int(round(h))), max(1, int(round(w))))
            preview = cv2.ellipse(preview, center, axes, -90 + float(rot_deg), 0.0, 360.0, (b, g, r), thickness=-1)
        return image_to_photo(preview)
    except Exception:
        return None


class App:
    def __init__(self, initial_images):
        ensure_dirs()
        self.root = Tk()
        self.root.title("forza-painter FH6")
        self.root.geometry("1180x780")
        self.lang = "en"
        self.queue = queue.Queue()
        self.settings = load_settings()
        self.images = [Path(path) for path in initial_images if Path(path).exists()]
        self.json_files = []
        self.outputs = []
        self.processes = []
        self.photo = None
        self.profile_buttons = []
        self.use_custom_settings = StringVar(value="0")
        self.custom_stop_at = StringVar()
        self.custom_max_resolution = StringVar()
        self.custom_random_samples = StringVar()
        self.custom_mutated_samples = StringVar()
        self.custom_save_at = StringVar()
        self.translated = []
        self.status = StringVar(value=tr(self.lang, "ready"))
        self.selected_profile = StringVar()
        self.selected_game = StringVar(value="fh6")
        self.selected_pid = StringVar()
        self.layer_count = StringVar()
        self.snapshot_count = StringVar()
        self.current_count = StringVar()
        self.count_address = StringVar()
        self.table_address = StringVar()
        self.inspect_table_value = StringVar()
        self.advanced_visible = False
        self._build()
        self.refresh_processes()
        if self.settings:
            self.selected_profile.set(self.settings[min(2, len(self.settings) - 1)]["label"])
            self._update_setting_description()
        self._render_lists()
        self._poll_queue()

    def _label(self, parent, key, **kwargs):
        widget = Label(parent, text=tr(self.lang, key), **kwargs)
        self.translated.append((widget, key, "text"))
        return widget

    def _button(self, parent, key, command, **kwargs):
        widget = Button(parent, text=tr(self.lang, key), command=command, **kwargs)
        self.translated.append((widget, key, "text"))
        return widget

    def _build(self):
        header = Frame(self.root)
        header.pack(fill=X, padx=14, pady=(12, 6))
        title_box = Frame(header)
        title_box.pack(side=LEFT, fill=X, expand=True)
        self._label(title_box, "title", font=("Segoe UI", 18, "bold"), anchor="w").pack(fill=X)
        self._label(title_box, "subtitle", anchor="w", fg="#555").pack(fill=X)
        right = Frame(header)
        right.pack(side=RIGHT)
        self._label(right, "language").pack(anchor="e")
        self.lang_combo = ttk.Combobox(right, values=["English", "中文"], state="readonly", width=10)
        self.lang_combo.set("English")
        self.lang_combo.pack(anchor="e")
        self.lang_combo.bind("<<ComboboxSelected>>", self._on_language)

        process_bar = Frame(self.root)
        process_bar.pack(fill=X, padx=14, pady=(0, 8))
        self._label(process_bar, "process").pack(side=LEFT)
        self.process_combo = ttk.Combobox(process_bar, textvariable=self.selected_pid, state="readonly", width=44)
        self.process_combo.pack(side=LEFT, padx=8)
        self._button(process_bar, "refresh", self.refresh_processes).pack(side=LEFT)
        Label(process_bar, textvariable=self.status, anchor="e").pack(side=RIGHT)

        self.tabs = ttk.Notebook(self.root)
        self.tabs.pack(fill=BOTH, expand=True, padx=14, pady=(0, 8))
        self.generate_tab = Frame(self.tabs)
        self.import_tab = Frame(self.tabs)
        self.tools_tab = Frame(self.tabs)
        self.tutorial_tab = Frame(self.tabs)
        self.tabs.add(self.generate_tab, text=tr(self.lang, "generate_tab"))
        self.tabs.add(self.import_tab, text=tr(self.lang, "import_tab"))
        self.tabs.add(self.tutorial_tab, text=tr(self.lang, "tutorial_tab"))

        self._build_generate_tab()
        self._build_import_tab()
        self._build_tools_tab()
        self._build_tutorial_tab()
        self._build_log()

    def _build_generate_tab(self):
        left_outer = Frame(self.generate_tab)
        left_outer.pack(side=LEFT, fill=BOTH, expand=True, padx=(0, 10), pady=10)
        right = Frame(self.generate_tab)
        right.pack(side=RIGHT, fill=BOTH, expand=True, pady=10)

        self._label(left_outer, "scroll_hint", anchor="w", justify=LEFT, fg="#8a5300").pack(fill=X, pady=(0, 6))
        left_canvas = Canvas(left_outer, highlightthickness=0)
        left_scroll = ttk.Scrollbar(left_outer, orient="vertical", command=left_canvas.yview)
        left_canvas.configure(yscrollcommand=left_scroll.set)
        left_canvas.pack(side=LEFT, fill=BOTH, expand=True, pady=(0, 8))
        left_scroll.pack(side=RIGHT, fill="y", pady=(0, 8))
        left = Frame(left_canvas)
        left_window = left_canvas.create_window((0, 0), window=left, anchor="nw")

        def _update_scroll_region(_event=None):
            left_canvas.configure(scrollregion=left_canvas.bbox("all"))

        def _match_canvas_width(event):
            left_canvas.itemconfigure(left_window, width=event.width)

        def _mousewheel(event):
            left_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        left.bind("<Configure>", _update_scroll_region)
        left_canvas.bind("<Configure>", _match_canvas_width)
        left_canvas.bind("<MouseWheel>", _mousewheel)
        left.bind("<MouseWheel>", _mousewheel)

        step1 = ttk.LabelFrame(left, text=tr(self.lang, "generate_step_image"))
        self.translated.append((step1, "generate_step_image", "text"))
        step1.pack(fill=X, pady=(0, 10))
        self._label(step1, "generate_step_image_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        row = Frame(step1)
        row.pack(fill=X, padx=10)
        self._label(row, "images").pack(side=LEFT)
        self._button(row, "add_images", self.add_images).pack(side=RIGHT)
        self.image_list = Listbox(step1, height=7)
        self.image_list.pack(fill=X, padx=10, pady=(6, 10))
        self.image_list.bind("<<ListboxSelect>>", self._preview_selected_image)

        step2 = ttk.LabelFrame(left, text=tr(self.lang, "generate_step_quality"))
        self.translated.append((step2, "generate_step_quality", "text"))
        step2.pack(fill=X, pady=(0, 10))
        self._label(step2, "generate_step_quality_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        self.profile_button_frame = Frame(step2)
        self.profile_button_frame.pack(fill=X, padx=10, pady=(6, 4))
        for item in self.settings:
            button = ttk.Radiobutton(
                self.profile_button_frame,
                text=item["label"],
                value=item["label"],
                variable=self.selected_profile,
                command=self._update_setting_description,
            )
            button.pack(anchor="w", pady=2)
            self.profile_buttons.append(button)
        self.setting_description = Label(step2, text="", anchor="w", justify=LEFT, wraplength=500)
        self.setting_description.pack(fill=X, padx=10, pady=(0, 10))
        custom_toggle = Checkbutton(
            step2,
            text=tr(self.lang, "custom_settings"),
            variable=self.use_custom_settings,
            onvalue="1",
            offvalue="0",
            command=self._sync_custom_state,
        )
        custom_toggle.pack(anchor="w", padx=10, pady=(0, 4))
        self.translated.append((custom_toggle, "custom_settings", "text"))
        custom_grid = Frame(step2)
        custom_grid.pack(fill=X, padx=10, pady=(0, 10))
        self.custom_fields = []
        custom_specs = [
            ("custom_layers", self.custom_stop_at),
            ("custom_resolution", self.custom_max_resolution),
            ("custom_random", self.custom_random_samples),
            ("custom_mutated", self.custom_mutated_samples),
            ("custom_save_at", self.custom_save_at),
        ]
        for row_index, (key, variable) in enumerate(custom_specs):
            label = self._label(custom_grid, key, anchor="w")
            label.grid(row=row_index, column=0, sticky="w", pady=2, padx=(0, 8))
            entry = Entry(custom_grid, textvariable=variable, width=18)
            entry.grid(row=row_index, column=1, sticky="ew", pady=2)
            self.custom_fields.append(entry)
        custom_grid.columnconfigure(1, weight=1)
        self._sync_custom_state()

        step3 = ttk.LabelFrame(left_outer, text=tr(self.lang, "generate_step_run"))
        self.translated.append((step3, "generate_step_run", "text"))
        step3.pack(fill=X)
        self._label(step3, "generate_step_run_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        actions = Frame(step3)
        actions.pack(fill=X, padx=10, pady=(4, 12))
        self._button(actions, "start_generate", self.start_generate, font=("Segoe UI", 12, "bold"), height=2).pack(side=LEFT, fill=X, expand=True)
        self._button(actions, "open_output", self.open_output_folder, height=2).pack(side=LEFT, padx=8)

        self._label(right, "preview", anchor="w", font=("Segoe UI", 12, "bold")).pack(fill=X)
        self.preview_label = Label(right, text=tr(self.lang, "preview_hint"), bg="#202020", fg="#dddddd", width=60, height=24)
        self.preview_label.pack(fill=BOTH, expand=True, pady=6)

    def _build_import_tab(self):
        left = Frame(self.import_tab)
        left.pack(side=LEFT, fill=BOTH, expand=True, padx=(0, 10), pady=10)
        right = Frame(self.import_tab)
        right.pack(side=RIGHT, fill=BOTH, expand=True, pady=10)

        step1 = ttk.LabelFrame(left, text=tr(self.lang, "step_game"))
        self.translated.append((step1, "step_game", "text"))
        step1.pack(fill=X, pady=(0, 10))
        self._label(step1, "step_game_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        game_row = Frame(step1)
        game_row.pack(fill=X, padx=10, pady=(0, 10))
        self._label(game_row, "game_profile").pack(side=LEFT)
        self.import_game_combo = ttk.Combobox(game_row, values=list(PROFILES.keys()), textvariable=self.selected_game, state="readonly", width=8)
        self.import_game_combo.pack(side=LEFT, padx=8)
        self._label(game_row, "pid").pack(side=LEFT)
        self.import_pid_entry = Entry(game_row, textvariable=self.selected_pid, width=30)
        self.import_pid_entry.pack(side=LEFT, padx=8)
        self._button(game_row, "refresh", self.refresh_processes).pack(side=LEFT)

        step2 = ttk.LabelFrame(left, text=tr(self.lang, "step_template"))
        self.translated.append((step2, "step_template", "text"))
        step2.pack(fill=X, pady=(0, 10))
        self._label(step2, "step_template_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        template_row = Frame(step2)
        template_row.pack(fill=X, padx=10, pady=(0, 10))
        self._label(template_row, "layer_count").pack(side=LEFT)
        Entry(template_row, textvariable=self.layer_count, width=18, font=("Segoe UI", 13)).pack(side=LEFT, padx=8)

        step3 = ttk.LabelFrame(left, text=tr(self.lang, "step_json"))
        self.translated.append((step3, "step_json", "text"))
        step3.pack(fill=BOTH, expand=True, pady=(0, 10))
        self._label(step3, "step_json_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        row = Frame(step3)
        row.pack(fill=X, padx=10)
        self._label(row, "json_files").pack(side=LEFT)
        self._button(row, "add_json", self.add_json).pack(side=RIGHT)
        self._button(row, "use_outputs", self.use_generated_outputs).pack(side=RIGHT, padx=8)
        self.json_list = Listbox(step3, height=10)
        self.json_list.pack(fill=BOTH, expand=True, padx=10, pady=6)
        self.json_list.bind("<<ListboxSelect>>", self._preview_selected_json)

        step4 = ttk.LabelFrame(right, text=tr(self.lang, "step_import"))
        self.translated.append((step4, "step_import", "text"))
        step4.pack(fill=X, pady=(0, 10))
        self._label(step4, "step_import_hint", anchor="w", justify=LEFT, wraplength=500).pack(fill=X, padx=10, pady=(8, 4))
        self._label(step4, "easy_import_hint", anchor="w", justify=LEFT, wraplength=500, fg="#555").pack(fill=X, padx=10, pady=4)
        self._label(step4, "admin_note", anchor="w", justify=LEFT, wraplength=500, fg="#8a5300").pack(fill=X, padx=10, pady=4)
        actions = Frame(step4)
        actions.pack(fill=X, padx=10, pady=12)
        self._button(actions, "import_json", self.start_import, font=("Segoe UI", 13, "bold"), height=2).pack(side=LEFT, fill=X, expand=True)
        self.advanced_button = self._button(actions, "show_advanced", self.toggle_advanced)
        self.advanced_button.pack(side=LEFT, padx=(8, 0))

        self.advanced_frame = ttk.LabelFrame(right, text=tr(self.lang, "advanced_options"))
        self.translated.append((self.advanced_frame, "advanced_options", "text"))
        self._field(self.advanced_frame, "manual_count", self.count_address, row=0)
        self._field(self.advanced_frame, "manual_table", self.table_address, row=1)
        self._button(self.advanced_frame, "auto_locate", self.start_auto_locate).grid(row=2, column=0, columnspan=2, sticky="ew", pady=(8, 4))

        self._label(right, "import_preview", anchor="w", font=("Segoe UI", 12, "bold")).pack(fill=X, pady=(8, 0))
        self.import_preview_label = Label(right, text=tr(self.lang, "preview_hint"), bg="#202020", fg="#dddddd", width=56, height=20)
        self.import_preview_label.pack(fill=BOTH, expand=True, pady=6)

    def _build_tools_tab(self):
        form = Frame(self.tools_tab)
        form.pack(fill=X, padx=10, pady=10)
        self._field(form, "layer_count", self.layer_count, row=0)
        self._field(form, "snapshot_count", self.snapshot_count, row=1)
        self._field(form, "current_count", self.current_count, row=2)
        self._field(form, "table_address", self.inspect_table_value, row=3)
        actions = Frame(self.tools_tab)
        actions.pack(fill=X, padx=10, pady=8)
        self._button(actions, "diagnose", self.start_diagnose).pack(side=LEFT)
        self._button(actions, "auto_locate", self.start_auto_locate).pack(side=LEFT, padx=6)
        self._button(actions, "save_snapshot", self.start_save_snapshot).pack(side=LEFT, padx=6)
        self._button(actions, "compare_snapshot", self.start_compare_snapshot).pack(side=LEFT, padx=6)
        self._button(actions, "inspect_table", self.start_inspect_table).pack(side=LEFT, padx=6)

    def _build_tutorial_tab(self):
        self.tutorial_text = Text(self.tutorial_tab, wrap="word")
        self.tutorial_text.pack(fill=BOTH, expand=True, padx=10, pady=10)
        self._update_tutorial()

    def _build_log(self):
        self._label(self.root, "logs", anchor="w").pack(fill=X, padx=14)
        self.log = Text(self.root, height=9)
        self.log.pack(fill=BOTH, padx=14, pady=(0, 12))

    def _field(self, parent, key, variable, row, values=None, readonly=False):
        self._label(parent, key, anchor="w").grid(row=row, column=0, sticky="w", padx=(0, 8), pady=5)
        if values:
            widget = ttk.Combobox(parent, values=values, textvariable=variable, state="readonly" if readonly else "normal")
        else:
            widget = Entry(parent, textvariable=variable)
        widget.grid(row=row, column=1, sticky="ew", pady=5)
        parent.columnconfigure(1, weight=1)
        return widget

    def _on_language(self, _event=None):
        self.lang = "zh" if self.lang_combo.get() == "中文" else "en"
        for widget, key, option in self.translated:
            try:
                widget.config(**{option: tr(self.lang, key)})
            except Exception:
                pass
        self.tabs.tab(self.generate_tab, text=tr(self.lang, "generate_tab"))
        self.tabs.tab(self.import_tab, text=tr(self.lang, "import_tab"))
        self.tabs.tab(self.tutorial_tab, text=tr(self.lang, "tutorial_tab"))
        if self.photo is None:
            self.preview_label.config(text=tr(self.lang, "preview_hint"))
            if hasattr(self, "import_preview_label"):
                self.import_preview_label.config(text=tr(self.lang, "preview_hint"))
        if hasattr(self, "advanced_button"):
            self.advanced_button.config(text=tr(self.lang, "hide_advanced" if self.advanced_visible else "show_advanced"))
        self._update_tutorial()
        self.status.set(tr(self.lang, "ready"))

    def _update_tutorial(self):
        self.tutorial_text.config(state="normal")
        self.tutorial_text.delete("1.0", END)
        self.tutorial_text.insert(END, tr(self.lang, "tutorial"))
        self.tutorial_text.config(state="disabled")

    def _update_setting_description(self):
        item = self._selected_setting()
        self.setting_description.config(text=item["description"] if item else "No settings profiles found.")
        if item and self.use_custom_settings.get() != "1":
            values = item.get("values", {})
            self.custom_stop_at.set(values.get("stopAt", "3000"))
            self.custom_max_resolution.set(values.get("maxResolution", "1200"))
            self.custom_random_samples.set(values.get("randomSamples", "3000"))
            self.custom_mutated_samples.set(values.get("mutatedSamples", "1000"))
            self.custom_save_at.set(values.get("saveAt", values.get("stopAt", "3000")))

    def _sync_custom_state(self):
        state = "normal" if self.use_custom_settings.get() == "1" else "disabled"
        for entry in getattr(self, "custom_fields", []):
            entry.config(state=state)
        if state == "disabled":
            self._update_setting_description()

    def _effective_setting(self):
        setting = self._selected_setting()
        if not setting or self.use_custom_settings.get() != "1":
            return setting
        custom = {
            "stopAt": self.custom_stop_at.get(),
            "maxResolution": self.custom_max_resolution.get(),
            "randomSamples": self.custom_random_samples.get(),
            "mutatedSamples": self.custom_mutated_samples.get(),
            "saveAt": self.custom_save_at.get(),
        }
        if not custom["saveAt"] and custom["stopAt"]:
            custom["saveAt"] = custom["stopAt"]
        return write_custom_settings(setting, custom)

    def toggle_advanced(self):
        self.advanced_visible = not self.advanced_visible
        if self.advanced_visible:
            self.advanced_frame.pack(fill=X, pady=(0, 10))
        else:
            self.advanced_frame.pack_forget()
        self.advanced_button.config(text=tr(self.lang, "hide_advanced" if self.advanced_visible else "show_advanced"))

    def _selected_setting(self):
        label = self.selected_profile.get()
        for item in self.settings:
            if item["label"] == label:
                return item
        return self.settings[0] if self.settings else None

    def _render_lists(self):
        self.image_list.delete(0, END)
        for path in self.images:
            self.image_list.insert(END, str(path))
        self.json_list.delete(0, END)
        for path in self.json_files:
            self.json_list.insert(END, str(path))

    def log_line(self, message):
        self.log.insert(END, f"[{time.strftime('%H:%M:%S')}] {message}\n")
        self.log.see(END)

    def friendly_generator_line(self, line):
        text = (line or "").strip()
        if not text:
            return None
        progress = re.match(r"\[(\d+)/(\d+)\]\s+(.*)", text)
        if progress:
            current, total, detail = progress.groups()
            if "Added rotated ellipse" in detail:
                return f"Generated layer {current}/{total}"
            if "Saved geometry checkpoint" in detail:
                return f"Saved JSON checkpoint {current}/{total}"
            if "Saved preview snapshot" in detail:
                return f"Updated preview {current}/{total}"
            if "Step completed" in detail:
                return None
            return None
        if text.startswith("Loaded image:"):
            return text
        if text.startswith("Settings:"):
            return text
        if text in ("FINISHED",):
            return text
        if "error" in text.lower() or "failed" in text.lower() or "panic" in text.lower():
            return text
        return None

    def add_images(self):
        files = filedialog.askopenfilenames(
            title="Choose images",
            filetypes=[("Images", "*.png *.jpg *.jpeg *.bmp"), ("All files", "*.*")],
        )
        for item in files:
            path = Path(item)
            if path.exists() and path not in self.images:
                self.images.append(path)
        self._render_lists()
        if files:
            self.show_preview(render_source_image(Path(files[0])))

    def add_json(self):
        files = filedialog.askopenfilenames(
            title="Choose geometry JSON",
            filetypes=[("Geometry JSON", "*.json"), ("All files", "*.*")],
        )
        for item in files:
            path = Path(item)
            if path.exists() and path not in self.json_files:
                self.json_files.append(path)
        self._render_lists()
        if files:
            self.show_preview(render_geometry_json(Path(files[0])))

    def use_generated_outputs(self):
        for path in self.outputs:
            if path.exists() and path not in self.json_files:
                self.json_files.append(path)
        self._render_lists()
        self.log_line(f"Added {len(self.outputs)} generated JSON file(s) to import list.")

    def _preview_selected_image(self, _event=None):
        selection = self.image_list.curselection()
        if selection:
            self.show_preview(render_source_image(self.images[selection[0]]))

    def _preview_selected_json(self, _event=None):
        selection = self.json_list.curselection()
        if selection:
            self.show_preview(render_geometry_json(self.json_files[selection[0]]))

    def show_preview(self, data):
        if not data:
            message = tr(self.lang, "preview_unavailable")
            self.preview_label.config(image="", text=message, bg="#202020")
            self.preview_label.image = None
            if hasattr(self, "import_preview_label"):
                self.import_preview_label.config(image="", text=message, bg="#202020")
                self.import_preview_label.image = None
            return
        self.photo = data
        image = PhotoImage(data=data)
        self.preview_label.config(image=image, text="", bg="#202020")
        self.preview_label.image = image
        if hasattr(self, "import_preview_label"):
            import_image = PhotoImage(data=data)
            self.import_preview_label.config(image=import_image, text="", bg="#202020")
            self.import_preview_label.image = import_image

    def show_preview_file(self, path):
        try:
            image = PhotoImage(file=str(path))
        except Exception:
            self.show_preview(None)
            return
        self.photo = image
        self.preview_label.config(image=image, text="", bg="#202020")
        self.preview_label.image = image
        if hasattr(self, "import_preview_label"):
            import_image = PhotoImage(file=str(path))
            self.import_preview_label.config(image=import_image, text="", bg="#202020")
            self.import_preview_label.image = import_image

    def refresh_processes(self):
        self.processes = game_processes()
        values = [item["label"] for item in self.processes]
        if not values:
            values = [tr(self.lang, "no_game")]
        self.process_combo["values"] = values
        if self.processes:
            self.selected_pid.set(values[0])
            self.selected_game.set(self.processes[0]["profile"])
        else:
            self.selected_pid.set("")

    def selected_pid_value(self):
        raw = self.selected_pid.get()
        match = re.search(r"pid\s+(\d+)", raw, re.I)
        if match:
            return int(match.group(1))
        try:
            return int(raw.strip())
        except ValueError:
            return None

    def start_generate(self):
        if not self.images:
            self.log_line("No images selected.")
            return
        setting = self._effective_setting()
        if not setting:
            self.log_line("No quality profile selected.")
            return
        if not GENERATOR_EXE.exists():
            self.log_line(f"Missing generator: {GENERATOR_EXE}")
            return
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=self._generate_worker, args=(setting,), daemon=True).start()

    def _generate_worker(self, setting):
        try:
            self.queue.put(("log", f"Selected profile: {setting['path'].name}"))
            for image_path in list(self.images):
                before = {path.resolve() for path in generated_jsons(image_path)}
                preview_path = generator_preview_path(image_path)
                if preview_path.exists():
                    try:
                        preview_path.unlink()
                    except OSError:
                        pass
                self.queue.put(("log", f"Generating: {image_path}"))
                self.queue.put(("preview", render_source_image(image_path)))
                flags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
                cmd = build_generator_command(image_path, setting)
                self.queue.put(("log", f"Running GPU generator with {setting['path'].name}"))
                proc = subprocess.Popen(
                    cmd,
                    cwd=ROOT,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    creationflags=flags,
                )

                last_preview = None
                last_preview_mtime = None
                last_progress_log = None
                while proc.poll() is None:
                    line = proc.stdout.readline()
                    if line:
                        friendly = self.friendly_generator_line(line)
                        if friendly and friendly != last_progress_log:
                            last_progress_log = friendly
                            self.queue.put(("log", friendly))
                    preview_files = generated_preview_files(image_path)
                    if preview_files:
                        newest_preview = preview_files[0]
                        preview_mtime = newest_preview.stat().st_mtime
                        if preview_mtime != last_preview_mtime:
                            last_preview_mtime = preview_mtime
                            self.queue.put(("preview_file", newest_preview))
                    newest = generated_jsons(image_path)
                    if newest and newest[0] != last_preview:
                        last_preview = newest[0]
                    time.sleep(0.1)
                for line in proc.stdout.read().splitlines():
                    friendly = self.friendly_generator_line(line)
                    if friendly and friendly != last_progress_log:
                        last_progress_log = friendly
                        self.queue.put(("log", friendly))
                if proc.returncode != 0:
                    self.queue.put(("log", f"Generator exited with code {proc.returncode}."))
                    self.queue.put(("status", tr(self.lang, "failed")))
                    return
                after = generated_jsons(image_path)
                new_outputs = best_geometry_jsons([path for path in after if path.resolve() not in before])
                if not new_outputs and after:
                    new_outputs = best_geometry_jsons(after[:1])
                if not new_outputs:
                    self.queue.put(("log", "Generator finished but no JSON output was found."))
                    self.queue.put(("status", tr(self.lang, "failed")))
                    return
                for output in new_outputs:
                    if output not in self.outputs:
                        self.outputs.append(output)
                    if output not in self.json_files:
                        self.json_files.append(output)
                    self.queue.put(("log", f"Generated: {output}"))
                    preview_files = generated_preview_files(image_path)
                    if preview_files:
                        self.queue.put(("preview_file", preview_files[0]))
                    else:
                        self.queue.put(("preview", render_geometry_json(output)))
            self.queue.put(("render_lists", None))
            self.queue.put(("status", tr(self.lang, "done")))
        except Exception as exc:
            self.queue.put(("log", f"Generator failed: {exc}"))
            self.queue.put(("status", tr(self.lang, "failed")))

    def open_output_folder(self):
        folder = None
        if self.outputs:
            folder = self.outputs[-1].parent
        elif self.images:
            folder = self.images[-1].parent
        if folder and folder.exists():
            os.startfile(folder)

    def run_subprocess(self, cmd, timeout=None):
        self.queue.put(("log", self._friendly_command_name(cmd)))
        flags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
        env = os.environ.copy()
        env.update({"FORZA_PAINTER_NO_ELEVATE": "1", "FORZA_PAINTER_NO_PAUSE": "1"})
        proc = subprocess.Popen(
            [str(x) for x in cmd],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            creationflags=flags,
            env=env,
        )
        started = time.time()
        while True:
            line = proc.stdout.readline()
            if line:
                friendly = self._friendly_subprocess_line(line.rstrip())
                if friendly:
                    self.queue.put(("log", friendly))
            if proc.poll() is not None:
                break
            if timeout and time.time() - started > timeout:
                proc.kill()
                self.queue.put(("log", f"Timed out after {timeout} seconds."))
                return 124
            time.sleep(0.05)
        for line in proc.stdout.read().splitlines():
            friendly = self._friendly_subprocess_line(line.rstrip())
            if friendly:
                self.queue.put(("log", friendly))
        return proc.returncode

    def _friendly_command_name(self, cmd):
        joined = " ".join(str(x) for x in cmd)
        if "fh6_probe.py" in joined and "--auto-locate" in joined:
            return tr(self.lang, "locating")
        if "main.py" in joined:
            return tr(self.lang, "importing")
        return "Starting helper..."

    def _check_json_layer_fit(self, json_path, layer_count):
        try:
            from generator_backend import geometry_shape_count
            json_layers = geometry_shape_count(json_path)
            template_layers = int(layer_count)
        except Exception:
            return
        usable_layers = max(0, template_layers - 4)
        if json_layers and template_layers and json_layers > usable_layers:
            self.queue.put(("log", f"{tr(self.lang, 'json_needs_more_template_layers')} JSON={json_layers}, template={template_layers}, usable={usable_layers}"))
        if json_layers and usable_layers and json_layers < usable_layers * 0.75:
            self.queue.put(("log", f"{tr(self.lang, 'json_too_small')} JSON={json_layers}, usable={usable_layers}"))

    def _friendly_subprocess_line(self, line):
        if not line:
            return None
        raw = line.strip()
        lower = raw.lower()
        noisy_parts = (
            "base:",
            "candidate score=",
            "layout candidate",
            "table[",
            "ptr=0x",
            "count=0x",
            "tablefield=",
            "wrote fh6 session location",
            "fh6 layout-count scan checked",
            "process: forzahorizon",
            "current values:",
            "loaded ",
            "descriptor @",
            "info found:",
            "vtp found:",
        )
        if any(part in lower for part in noisy_parts):
            return None
        if "fast fh6 layer group candidates:" in lower:
            return tr(self.lang, "located")
        if "no safe fh6 layer group" in lower:
            return tr(self.lang, "safe_stop")
        if "auto-locating fh6 layer count/table" in lower:
            return tr(self.lang, "locating")
        if "cliverylayer table found" in lower:
            return tr(self.lang, "located")
        if "forza horizon 6 detected" in lower:
            return raw
        if raw.startswith("Writing layer") or raw == "DONE!" or raw.startswith("The ideal background color"):
            return raw
        if "openprocess" in lower or "error" in lower or "failed" in lower or "traceback" in lower:
            return raw
        if raw.startswith("<class 'SystemExit'>") or raw.startswith("SystemExit: 0"):
            return None
        return raw

    def start_auto_locate(self):
        pid = self.selected_pid_value()
        layer_count = self.layer_count.get().strip()
        if not pid or not layer_count:
            self.log_line("PID and template layer count are required.")
            return
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=self._auto_locate_worker, args=(pid, layer_count), daemon=True).start()

    def _auto_locate_worker(self, pid, layer_count):
        cmd = [
            sys.executable,
            ROOT / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(layer_count),
            "--auto-locate",
            "--write-session",
            SESSION_PATH,
            "--limit-mb",
            str(MEMORY_SNAPSHOT_LIMIT_MB),
            "--max-matches",
            "500000",
            "--inspect-radius",
            "0x800",
            "--max-seconds",
            "45",
        ]
        code = self.run_subprocess(cmd, timeout=70)
        if code == 0 and SESSION_PATH.exists():
            session = load_session_location()
            if session:
                self.queue.put(("log", tr(self.lang, "located")))
        self.queue.put(("status", tr(self.lang, "done") if code == 0 else tr(self.lang, "failed")))

    def start_import(self):
        if not self.json_files:
            self.log_line("No JSON files selected.")
            return
        pid = self.selected_pid_value()
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=self._import_worker, args=(pid,), daemon=True).start()

    def _import_worker(self, pid):
        game = self.selected_game.get() or "fh6"
        count_address = parse_hex_or_empty(self.count_address.get())
        table_address = parse_hex_or_empty(self.table_address.get())
        layer_count = self.layer_count.get().strip()
        if not count_address and not table_address and game == "fh6":
            session = load_session_location()
            session_count_matches = session and str(session.get("layer_count", "")) == str(layer_count)
            if session and session_count_matches and session_pid_is_live(session, game) and (not pid or int(pid) == int(session.get("pid", -1))):
                pid = int(session["pid"])
                count_address = "0x{:x}".format(int(session["count_address"]))
                table_address = "0x{:x}".format(int(session["table_address"]))
                self.queue.put(("log", tr(self.lang, "located")))
            elif pid and layer_count:
                self.queue.put(("log", tr(self.lang, "locating")))
                self._auto_locate_worker(pid, layer_count)
                session = load_session_location()
                if session and str(session.get("layer_count", "")) == str(layer_count) and session_pid_is_live(session, game):
                    count_address = "0x{:x}".format(int(session["count_address"]))
                    table_address = "0x{:x}".format(int(session["table_address"]))
                    self.queue.put(("log", tr(self.lang, "located")))
                else:
                    self.queue.put(("status", tr(self.lang, "failed")))
                    return
        for path in list(self.json_files):
            if game == "fh6" and layer_count:
                self._check_json_layer_fit(path, layer_count)
            cmd = [sys.executable, ROOT / "main.py", "--game", game, "--no-preview"]
            if pid:
                cmd.extend(["--pid", str(pid)])
            if count_address:
                cmd.extend(["--layer-count-address", count_address])
            if table_address:
                cmd.extend(["--layer-table-address", table_address])
            if game == "fh6" and layer_count:
                cmd.extend(["--layer-count-value", str(layer_count)])
            cmd.append(path)
            code = self.run_subprocess(cmd)
            if code != 0:
                self.queue.put(("status", tr(self.lang, "failed")))
                return
        self.queue.put(("status", tr(self.lang, "done")))

    def start_diagnose(self):
        pid = self.selected_pid_value()
        cmd = [sys.executable, ROOT / "main.py", "--game", self.selected_game.get() or "fh6", "--diagnose"]
        if pid:
            cmd.extend(["--pid", str(pid)])
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 120), daemon=True).start()

    def start_save_snapshot(self):
        pid = self.selected_pid_value()
        count = self.snapshot_count.get().strip() or self.layer_count.get().strip()
        if not pid or not count:
            self.log_line("PID and snapshot layer count are required.")
            return
        output_path = PROBE_DIR / f"memory-count-{count}.jsonl"
        cmd = [
            sys.executable,
            ROOT / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(count),
            "--save-memory-snapshot",
            output_path,
            "--limit-mb",
            str(MEMORY_SNAPSHOT_LIMIT_MB),
        ]
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 360), daemon=True).start()

    def start_compare_snapshot(self):
        pid = self.selected_pid_value()
        previous = self.snapshot_count.get().strip()
        current = self.current_count.get().strip() or self.layer_count.get().strip()
        if not pid or not previous or not current:
            self.log_line("PID, snapshot layer count, and current layer count are required.")
            return
        snapshot_path = PROBE_DIR / f"memory-count-{previous}.jsonl"
        candidates_path = PROBE_DIR / f"memory-count-{previous}-to-{current}-candidates.json"
        intersect_path = PROBE_DIR / f"memory-count-{int(previous) - 1}-to-{previous}-candidates.json"
        cmd = [
            sys.executable,
            ROOT / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(current),
            "--compare-memory-snapshot",
            snapshot_path,
            "--write-candidates",
            candidates_path,
            "--max-matches",
            "50000",
        ]
        if intersect_path.exists():
            cmd.extend(["--intersect-candidates", intersect_path])
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 360), daemon=True).start()

    def start_inspect_table(self):
        pid = self.selected_pid_value()
        table = self.inspect_table_value.get().strip()
        count = self.layer_count.get().strip()
        if not pid or not table or not count:
            self.log_line("PID, layer count, and table address are required.")
            return
        cmd = [
            sys.executable,
            ROOT / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(count),
            "--inspect-table",
            table,
            "--inspect-layers",
            "12",
        ]
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 60), daemon=True).start()

    def _run_command_worker(self, cmd, timeout):
        code = self.run_subprocess(cmd, timeout=timeout)
        self.queue.put(("status", tr(self.lang, "done") if code == 0 else tr(self.lang, "failed")))

    def _poll_queue(self):
        while True:
            try:
                kind, payload = self.queue.get_nowait()
            except queue.Empty:
                break
            if kind == "log":
                self.log_line(payload)
            elif kind == "status":
                self.status.set(payload)
            elif kind == "preview":
                self.show_preview(payload)
            elif kind == "preview_file":
                self.show_preview_file(payload)
            elif kind == "render_lists":
                self._render_lists()
        self.root.after(100, self._poll_queue)

    def run(self):
        self.root.mainloop()


def main():
    parser = argparse.ArgumentParser(description="Standalone forza-painter FH6 desktop app.")
    parser.add_argument("images", nargs="*", help="Optional image files to preload.")
    args = parser.parse_args()
    App(args.images).run()


if __name__ == "__main__":
    main()
